[package]
name = "rust-gitaudit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = "z"
lto = true

[lib]
crate-type = ["bin"]

[build]
target = "x86_64-unknown-linux-musl"
