name: Create Release

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set release tag
        id: set_tag
        run: |
          tag=$(git rev-parse --short=8 ${{ github.sha }})
          echo "::set-output name=tag::${tag}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          release_name: ${{ steps.set_tag.outputs.tag }}
          body: ${{ steps.create_release.outputs.message }}
          draft: false
          prerelease: false
