name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_version.outputs.version }}
      version_without_v: ${{ steps.set_version.outputs.version_without_v }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set version
        id: set_version
        run: |
          # Extract current version from Cargo.toml
          current_version=$(grep -m 1 'version = "[0-9]*\.[0-9]*\.[0-9]*"' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $current_version"
          
          # Check if commit message contains version bump indicators
          commit_msg=$(git log -1 --pretty=%B)
          if [[ "$commit_msg" == *"#major"* ]]; then
            # Increment the major version
            new_version=$(echo $current_version | awk -F. '{print $1+1".0.0"}')
          elif [[ "$commit_msg" == *"#minor"* ]]; then
            # Increment the minor version
            new_version=$(echo $current_version | awk -F. '{print $1"."$2+1".0"}')
          else
            # Increment the patch version by default
            new_version=$(echo $current_version | awk -F. '{print $1"."$2"."$3+1}')
          fi
          
          echo "New version: $new_version"
          
          # Update version in Cargo.toml
          sed -i "s/^version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$new_version\"/" Cargo.toml
          
          # Set outputs for later steps
          echo "version=v$new_version" >> $GITHUB_OUTPUT
          echo "version_without_v=$new_version" >> $GITHUB_OUTPUT

      - name: Commit version update
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Cargo.toml
          git commit -m "Bump version to ${{ steps.set_version.outputs.version }}"
          git push

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.set_version.outputs.version_without_v }}
          name: ${{ steps.set_version.outputs.version_without_v }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-freebsd:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main  # Ensure we're using the updated code with version bump

    - name: Install Rust
      run: rustup update stable

    - name: Install cross-compilation tools
      uses: taiki-e/setup-cross-toolchain-action@v1
      with:
        target: x86_64-unknown-freebsd
    - run: cargo build --release
    - run: cp target/x86_64-unknown-freebsd/release/gitgud ./gitgud-freebsd-x86_64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: gitgud-freebsd-x86_64
        path: gitgud-freebsd-x86_64

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.create-release.outputs.version_without_v }}
        files: gitgud-freebsd-x86_64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build for Linux x86-64
      run: |
        apt update && apt install musl-tools -y
        rustup target add x86_64-unknown-linux-musl
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc
        export CC=aarch64-linux-gnu-gcc
        cargo build --release --target x86_64-unknown-linux-musl
        cp target/x86_64-unknown-linux-musl/release/gitgud ./gitgud-linux-x86_64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: gitgud-linux-x86_64
        path: gitgud-linux-x86_64

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.create-release.outputs.version_without_v }}
        files: gitgud-linux-x86_64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macOS-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build for macOS
      run: |
        rustup target add x86_64-apple-darwin
        cargo build --release --target x86_64-apple-darwin
        cp target/x86_64-apple-darwin/release/gitgud ./gitgud-darwin-x86_64

    - name: Build for macOS arm64
      run: |
        rustup target add aarch64-apple-darwin
        cargo build --release --target aarch64-apple-darwin
        cp target/aarch64-apple-darwin/release/gitgud ./gitgud-darwin-arm64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: macos-binaries-${{ needs.create-release.outputs.version_without_v }}
        path: |
          gitgud-darwin-x86_64
          gitgud-darwin-arm64

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.create-release.outputs.version_without_v }}
        files: |
          gitgud-darwin-x86_64
          gitgud-darwin-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest
    needs: create-release

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-msvc

    - name: Build for Windows x86-64
      run: |
        cargo build --release --target x86_64-pc-windows-msvc
        cp target/x86_64-pc-windows-msvc/release/gitgud.exe ./gitgud-windows-x86_64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: gitgud-windows-x86_64
        path: gitgud-windows-x86_64

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ needs.create-release.outputs.version_without_v }}
        files: gitgud-windows-x86_64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
