name: Build for FreeBSD x86_64

on:
  push:
    branches:
      - main

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup update stable

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: x86_64-unknown-freebsd
      - run: cargo build --release
      - run: cp target/x86_64-unknown-freebsd/release/rust-gitaudit ./rust-gitaudit-freebsd-x86_64

      - name: Get release ID
        id: get_release_id
        run: echo "::set-output name=id::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.id')"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: |
            rust-gitaudit-freebsd-x86_64

      - name: Attach binaries to release
        id: attach_artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release_id.outputs.id }}/assets?name=rust-gitaudit-freebsd-x86_64
          asset_path: rust-gitaudit-freebsd-x86_64
          asset_name: rust-gitaudit-freebsd-x86_64
          asset_content_type: application/octet-stream
