name: Build for FreeBSD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        run: rustup update stable

      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: x86_64-unknown-freebsd
      - run: cargo build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: rust-gitaudit
        path: target/x86_64-unknown-freebsd/debug/rust_gitaudit
