name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build for Linux x86-64
      run: |
        rustup target add x86_64-unknown-linux-gnu
        cargo build --release --target x86_64-unknown-linux-gnu
        cp target/x86_64-unknown-linux-gnu/release/rust-gitaudit ./rust-gitaudit-linux-x86_64

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          This is an example release.
        draft: true
        prerelease: false

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: |
          rust-gitaudit-linux-x86_64

    - name: Attach binaries to release
      id: attach_artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: rust-gitaudit-linux-x86_64
        asset_name: rust-gitaudit-linux-x86_64
        asset_content_type: application/octet-stream
